language: java
sudo: false
jdk:
  - oraclejdk8
env:
  - ISOLATED=true

after_success:
  - mvn clean verify jacoco:report coveralls:report

addons:
    code_climate:
        repo_token: 08f3bf247333d7cec88a3fb3117548542f921baad23a4dd4d818ad6c649a75a1  