language: java
sudo: false
jdk:
  - oraclejdk8
env:
  - ISOLATED=true

  - IntegrationTests:
        - after_success:
              - mvn clean test jacoco:report coveralls:report

after_success:
  - mvn clean test jacoco:report coveralls:report -DskipTests